create table category
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(255),
    description varchar(4000)
);

create table manufacturers
(
    id                   bigint generated by default as identity
        primary key,
    name                 varchar(255),
    manufacturer_address varchar(255)
);

create table product
(
    id              bigint generated by default as identity
        primary key,
    name            varchar(255),
    price           double precision,
    quantity        integer,
    category_id     bigint references category,
    manufacturer_id bigint references manufacturers
);

create table shop_users
(
    username                   varchar(255)
        primary key,
    password                   varchar(255),
    name                       varchar(255),
    surname                    varchar(255),
    is_account_non_expired     boolean default true,
    is_account_non_locked      boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled                 boolean default true,
    role                       varchar(50)
);

create table shopping_cart
(
    id            bigint generated by default as identity
        primary key,
    date_created  timestamp,
    user_username varchar(255) references shop_users,
    status        varchar(50)
);

create table shopping_cart_products
(
    shopping_cart_id bigint references shopping_cart on delete cascade,
    products_id      bigint references product on delete cascade,
    primary key (shopping_cart_id, products_id)
);


create index idx_cart_user_status on shopping_cart (user_username, status);
create index idx_user_username_password on shop_users (username, password);
create index idx_user_username on shop_users (username);
create index idx_user_role on shop_users (role);
